#!/usr/bin/env bash
#installs and configures nginx

sudo apt-get -y install nginx
sudo chown -R $User:$USER /var/www/html/index.ngix-debian.html
sudo echo "Hello World!">/var/www/html/index.ngix-debian.html
sudo service nginx restart
