#!/usr/bin/env bash
# Adds a 301 redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/listen 80 default_server/a \\trewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx start
