#!/usr/bin/env bash
# Adds a 301 redirection


sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

sudo service nginx start
