#!/usr/bin/env bash
# Adds a 301 redirection

new_string='\\tlocation /redirect_me {\n\t\treturn 301 http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n       }'

sudo sed -i '/^server {/a '"$new_string" /etc/nginx/sites-available/default
