#!/usr/bin/env bash
# Adds a 301 redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
#echo "Hello World" | sudo tee /var/www/html/index.html
#sudo sed -i '/listen 80 default_server/a \        rewrite ^/redirect_me https://https://#www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
#echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
#sudo sed -i "/index.nginx-debian.html;/a \        error_page 404 /custom_404.html;" /etc#/nginx/sites-available/default
#sudo service nginx restart
