#!/usr/bin/env bash
#test trap of signals

file=/var/run/myscript.pid

echo $$ >"$file"

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo i hate the kill command; rm $file; exit' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'rm $file; exit' SIGQUIT

done