#!/usr/bin/env bash
#process manager



cm="$1"
file="/var/run/my_process.pid"

if [ "$cm" = start ]
then
    ./manage_my_process &
    echo "$!" >"$file"
    echo "manage_my_process started"
elif [ "$cm" = stop ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm "$file"
elif [ "$cm" = restart ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm "$file"
    ./manage_my_process &
    echo "$!" >"$file"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
