#!/usr/bin/env bash
#iterates 10 times
#displays bad luck on the fourth iteration
#displays good luck on the eigth iterarion
#and best school for other iterations

i=0

while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	((i++))
done