#!/usr/bin/env bash
#4 and 8 in the chinese culture

i=0

while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done