#!/usr/bin/env bash
#loops to 20 while printing strings intermitently

i=0

while [ "$i" -lt 20 ]
do
	echo "$i"
	case "$i" in
	     4)
		echo  "bad luck from China"
		;;
	    9)
		echo "bad luck from Japan"
	   	;;
	    17)
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done