#!/usr/bin/env bash
#superstitious numbers

i=1

while [ "$i" -le 20 ]
do
	echo "$i"

	if [ "$i" -eq 4 ]
	then
		echo "bad luck fem China"
	elif [ "$i" -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ "$i" -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	((i++))
done