#!/usr/bin/env bash
#checks for properties of a file

name="./school"

if [ -e "$name" ]
then
	echo "school file exists"
	if [ -s "$name" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$name" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi