#!/usr/bin/env bash
#changes nginx ownership
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo pkill -f nginx
sudo -u nginx service nginx start
