#!/usr/bin/env bash
#changes nginx ownership
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill -f apache2
sudo pkill -f nginx
sudo -u nginx service nginx start
