#!/usr/bin/env bash
#changes nginx ownership
groupadd -r nginx
useradd nginx -r -g nginx -d /var/cache/nginx -s /sbin/nologin
chmod 755 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo pkill -f nginx
sudo -u nginx service nginx start
